### ISSUE TITLE
Time of release?

### ISSUE THREAD

**Issue by zhanggenex** [compsec-snu/razzer#1]
Your paper **Razzer: Finding Kernel Race Bugs through Fuzzing** is definately well written and we all appreciate this amazing work. But may I ask when will this code be released? Since your paper mentioned that 

> We will open source of RAZZER such that kernel developers and researchers can beneft from using RAZZER.

We will truely appreciate that.

**Comment by lifeasageek** [comment]
Hi,

Yes, we will surely release the code before Oakland (May 2019). The actual release should be much earlier than that, probably before the end of this year.

Thanks!
Byoungyoung

**Comment by srikanth007m** [comment]
@lifeasageek Any plan to release the source code?

**Comment by daydayup40** [comment]
@lifeasageek Hello, I'm intereted in the implemention of Razzer. When do you plan to release the project(or part of your code)? Thanks!

**Comment by zhangysh1995** [comment]
Any updates?

**Comment by lifeasageek** [comment]
Released the code now. I guess it won't be easy to run (as it requires several quirky configuration steps), and hope someone helps us out to add more complete documents.
