### ISSUE TITLE
kernel-build error

### ISSUE THREAD

**Issue by zizhiyoumu-fuzz** [compsec-snu/razzer#11]
While I use build-kernel.sh ，I found that kernel build is error:
undefined reference to `kmalloc'
how to deal with it?
Thanks!

**Comment by lifeasageek** [comment]
If you were building the kernel for static analysis (which is using LLVMLinux), you may ignore that error (suppose that is the link error). As long as you generated all built-in.bc files, the static analysis should be working as expected.
