### ISSUE TITLE
How to get built-in.bc?

### ISSUE THREAD

**Issue by ZIllR0** [compsec-snu/razzer#16]
When I use ./build.sh to compile linux-4.10.1, I can't get the **built-in.bc** files .
Do I need some patch?

**Comment by ZIllR0** [comment]
I got it

**Comment by bsauce** [comment]
> I got it

I find that `tools/llvmlinux/targets/x86_64/build-kernel.sh` use `CC=$GCC_HOME/install/bin/gcc` to get built-in.bc. How is it possible? Why not use Clang?
