### ISSUE TITLE
Links to C repro in Trophies are unavailable

### ISSUE THREAD

**Issue by c2hpxq** [compsec-snu/razzer#17]
Hi,

I'm interested in razzer and I want to inspect race cases reported by razzer. It seems that links to C repro & kernel config in lkml are unavailable now.

Are they still available somewhere? Since I don't have enough memory(less than 16GB, not enough even under N_PROC = 1), it's hard for me to perform complete static analysis of razzer. So it's problematic for me to get razzer work at full speed and it helps a lot if those C repros & config are still available.

Thanks in advance.

**Comment by lifeasageek** [comment]
Unfortunately, we don't have the generated code now :-(

**Comment by c2hpxq** [comment]
> Unfortunately, we don't have the generated code now :-(

Ok, thank you for your reply!
