### ISSUE TITLE
Cannot access Reproducer link in the mailing list

### ISSUE THREAD

**Issue by mudongliang** [compsec-snu/razzer#6]
The reproducer and config file links seem invalid in [BUG: soft lockup in snd_virmidi_output_trigger](https://lkml.org/lkml/2018/7/26/73).

**Comment by lifeasageek** [comment]
I'm not sure whether we still have a reproducer for that bug. You may refer to the log that Syzkaller reported at https://syzkaller.appspot.com/bug?id=642c927972318775e0ea1b4779ccd8624ce9e6f5

**Comment by mudongliang** [comment]
Sorry to reply late. There is no any reproducer in syzkaller. Please help doublecheck your dataset. Even if you only find the repro with system call sequence (not C reproducer) generated by syzkaller, it is also helpful. Thanks in advance.

**Comment by lifeasageek** [comment]
Pushed that repro: https://github.com/compsec-snu/razzer/blob/master/docs/repro-examples/repro-BUG-soft-lockup-in-snd_virmidi_output_trigger.c
